site_name: Website
site_url: https://statcan.github.io/hackathon-ginyu-force
site_description:
copyright: Copyright &copy; 2020 Statistics Canada
strict: true

docs_dir: docs
site_dir: site

repo_name: StatCan/hackathon-ginyu-force
repo_url: https://github.com/StatCan/hackathon-ginyu-force
edit_uri: edit/main/docs

theme:
  name: material
  language: en
  palette:
    primary: indigo
    accent: teal
  show_sidebar: false
  #logo: images/statcan.png

markdown_extensions:
  - toc:
      baselevel: 2
      permalink: true
  - attr_list
  - admonition
  - codehilite
  - mdx_truly_sane_lists
  - pymdownx.details

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/StatCan/hackathon-ginyu-force

# Page tree
nav:
  - Getting Started: index.md
  - Help/Contact: help.md
