name: Publish
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      #- name: Build
      #  uses: helaili/jekyll-action@v2
      #  with:
      #    jekyll_src: 'website'
      #    build_only: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Build
        run: |
          # Replace vars using jinja templates
          python3 .github/scripts/substitute.py dummy-values.json
      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
